name:: Jaga Supabase Tetap Aktif

on:
  schedule:
  #berjalan otomatis setiap hari Senin dan Kamis jam 09.00 UTC
  - cron: '0 9 * * 1,4'
  workflow_dispatch: #memungkinkan Anda menjalankan ping manual lewat GitHub

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
    - name: Kirim request ke Supabase API
      run: |
      curl -X GET "${{ secrets.https://rdlvuazpafvjuqvqlndw.supabase.co }}/rest/v1" \
      -H "apikey: ${{ secrets.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkbHZ1YXpwYWZ2anVxdnFsbmR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODEzMDYzODMsImV4cCI6MjA5Njg4MjM4M30.VzI58NQtSQ_iODJraIcgCgDB0gmvL2uTSZGr2l3Ps8g }}" \
      -H "Authorization: Bearer ${{ secrets.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkbHZ1YXpwYWZ2anVxdnFsbmR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODEzMDYzODMsImV4cCI6MjA5Njg4MjM4M30.VzI58NQtSQ_iODJraIcgCgDB0gmvL2uTSZGr2l3Ps8g }}"
